### ISSUE TITLE
Automatically appending the filename to cmd has been deprecated

### ISSUE THREAD

**Issue by ismell** [rwols/SublimeLinter-contrib-clang-tidy#2]
I see the following in the console: Automatically appending the filename to cmd has been deprecated. Use $file, $temp_file or $file_on_disk instead.

**Comment by mheinzler** [comment]
Can you check that you are using the latest release? This has been fixed last year.

**Comment by ismell** [comment]
It says I'm using 1.1.0. Not sure if I was some how running an old version.
