### ISSUE TITLE
compile_commands does not support ~ or $HOME

### ISSUE THREAD

**Issue by ismell** [rwols/SublimeLinter-contrib-clang-tidy#3]
Could we some how define the attribute in the [default attributes](http://www.sublimelinter.com/en/stable/linter_attributes.html#defaults) so it gets expanded added automatically?

**Comment by mheinzler** [comment]
I think this would be a good idea and also makes this setting a real linter setting. I will take a look at it.

**Comment by mheinzler** [comment]
@ismell Can you test PR #5? After changing your settings this should allow you to use ~.

**Comment by ismell** [comment]
It works. Thanks!
